# Generated by Django 4.1.7 on 2023-03-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category_post_created_at_post_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('BlockChain', 'BlockChain Technology'), ('AI', 'Technology'), ('NFT', 'NFT Technology'), ('BACKEND', 'BACKEND Technology'), ('FRONTEND', 'FRONTEND Technology')], max_length=50),
        ),
    ]
